// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddSharedPaths(arg1:Array<string>):Promise<void>;

export function ClearSharedItems():Promise<void>;

export function ConfirmDirectoryMode():Promise<boolean>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetFileList(arg1:string,arg2:string):Promise<Array<model.FileInfo>>;

export function GetShareConfig():Promise<model.ShareConfig>;

export function GetWiFiAddress():Promise<string>;

export function GetWiFiQRCode():Promise<string>;

export function ListDevices():Promise<Array<model.Device>>;

export function RemoveSharedItem(arg1:string):Promise<void>;

export function SelectFilesToShare():Promise<number>;

export function SelectFolderToShare():Promise<boolean>;

export function SelectRootDir():Promise<boolean>;

export function SelectUploadDir():Promise<boolean>;

export function SetRootDir(arg1:string):Promise<void>;

export function SetShareMode(arg1:string):Promise<void>;

export function SetUploadDir(arg1:string):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string):Promise<void>;
