// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function GetFileList(arg1, arg2) {
  return window['go']['main']['App']['GetFileList'](arg1, arg2);
}

export function GetWiFiAddress() {
  return window['go']['main']['App']['GetWiFiAddress']();
}

export function GetWiFiQRCode() {
  return window['go']['main']['App']['GetWiFiQRCode']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3);
}
