// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1: string): Promise<string>;

export interface Device {
    id: string;
    name: string;
    type: string;
    status: string;
}

export interface FileInfo {
    name: string;
    path: string;
    size: number;
    isDir: boolean;
    modTime: string;
}

export function ListDevices(): Promise<Device[]>;
export function GetFileList(deviceId: string, path: string): Promise<FileInfo[]>;
export function Download(deviceId: string, remotePath: string, localPath: string): Promise<void>;
export function Upload(deviceId: string, localPath: string, remotePath: string): Promise<void>;
export function GetWiFiAddress(): Promise<string>;
export function GetWiFiQRCode(): Promise<string>;
