// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Download(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetFileList(arg1:string,arg2:string):Promise<Array<model.FileInfo>>;

export function GetWiFiAddress():Promise<string>;

export function GetWiFiQRCode():Promise<string>;

export function ListDevices():Promise<Array<model.Device>>;

export function Upload(arg1:string,arg2:string,arg3:string):Promise<void>;
