// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSharedPaths(arg1) {
  return window['go']['main']['App']['AddSharedPaths'](arg1);
}

export function ClearSharedItems() {
  return window['go']['main']['App']['ClearSharedItems']();
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function GetFileList(arg1, arg2) {
  return window['go']['main']['App']['GetFileList'](arg1, arg2);
}

export function GetShareConfig() {
  return window['go']['main']['App']['GetShareConfig']();
}

export function GetWiFiAddress() {
  return window['go']['main']['App']['GetWiFiAddress']();
}

export function GetWiFiQRCode() {
  return window['go']['main']['App']['GetWiFiQRCode']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function RemoveSharedItem(arg1) {
  return window['go']['main']['App']['RemoveSharedItem'](arg1);
}

export function SetRootDir(arg1) {
  return window['go']['main']['App']['SetRootDir'](arg1);
}

export function SetShareMode(arg1) {
  return window['go']['main']['App']['SetShareMode'](arg1);
}

export function SetUploadDir(arg1) {
  return window['go']['main']['App']['SetUploadDir'](arg1);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3);
}
